ibtracert: Move getting of routes into function and add ability to specify lids/guids in a file
linux-rdma/infiniband-diags pull request #9
Opened 2018-03-26 12:18 UTC by hnrose

Reformatted version of skcoulter's PR #7

2018-03-28 17:52 UTC, skcoulter commented
Looks great - Thanx Hal !

2018-04-01 14:09 UTC, weiny2 approved these changes

2018-04-01 14:23 UTC, weiny2 requested changes

2018-04-01 14:23 UTC, weiny2 commented on src/ibtracert.c
> +				if (sscanf(portsbuf, "%s %s", srcbuf, dstbuf) != 2)
this allows srcbuf and dstbuf to be overrun.

We should use %20s for the specifiers.

2018-04-01 14:23 UTC, weiny2 commented on src/ibtracert.c
> +			if (portsbuf[l - 1] != '\n')
I'm not exactly sure what this check is for.  len(portsbuf) > len(srcbuf) + len(dstbuf)
And srcbuf and dstbuf is what we are concerned with.  I'm not opposed to this check but really we should be checking for overflow of the [src|dst]buf

2018-04-01 14:23 UTC, weiny2 commented on doc/rst/common/sec_ports-file.rst
> +The ports file can be used to specify multiple source and destination pairs that are not sequential in nature.  They can be lids or guids.  If guids, use the -G option to indicate that.
NIT: Why does sequential or not matter?

2018-04-02 21:23 UTC, hnrose commented on src/ibtracert.c
> +				if (sscanf(portsbuf, "%s %s", srcbuf, dstbuf) != 2)
Done

2018-04-02 21:24 UTC, hnrose commented on src/ibtracert.c
> +			if (portsbuf[l - 1] != '\n')
I removed this check.

2018-04-02 21:24 UTC, hnrose commented on doc/rst/common/sec_ports-file.rst
> +The ports file can be used to specify multiple source and destination pairs that are not sequential in nature.  They can be lids or guids.  If guids, use the -G option to indicate that.
I removed the additional words which seem extraneous.

2018-04-03 08:06 UTC, weiny2 commented on src/ibtracert.c
> +			if (portsbuf[0] != '#') {
Susan,

A follow up patch would be nice to make this work if the comment is not at the beginning of the line...  But this will be fine for now.

2018-04-03 08:06 UTC, weiny2 approved these changes

2018-04-03 08:07 UTC, merged